name: Build and Release

on:
  push:
    tags:
      - 'v*' # 当推送带有 v 前缀的标签时触发，例如 v1.0.0

# 添加权限配置
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整的历史记录，用于生成更新日志
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build extension
        run: yarn build
      
      - name: Zip extension
        run: |
          cd dist
          zip -r ../codeforge-toolkit-${{ github.ref_name }}.zip *
          cd ..
      
      - name: Generate changelog
        id: changelog
        run: |
          # 提取当前标签版本
          VERSION=${GITHUB_REF#refs/tags/}
          
          # 从CHANGELOG.md中提取该版本的更新内容
          CHANGELOG_CONTENT=$(awk -v ver="$VERSION" '
          BEGIN { found=0; content=""; }
          /^## \[/ { 
            if (found) exit;
            if ($0 ~ ver) found=1; 
          }
          { if (found && $0 !~ /^## \[/) content = content $0 "\n"; }
          END { print content; }
          ' CHANGELOG.md)
          
          # 如果没有找到特定版本的更新内容，则使用整个CHANGELOG
          if [ -z "$CHANGELOG_CONTENT" ]; then
            CHANGELOG_CONTENT=$(cat CHANGELOG.md)
          fi
          
          # 将更新内容写入输出变量
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: codeforge-toolkit-${{ github.ref_name }}.zip
          name: CodeForge ${{ github.ref_name }}
          body: |
            # CodeForge ${{ github.ref_name }}
            
            ## 更新内容
            
            ${{ steps.changelog.outputs.changelog }}
            
            ## 安装方法
            
            1. 下载 `codeforge-toolkit-${{ github.ref_name }}.zip` 文件
            2. 解压缩到本地文件夹
            3. 在 Chrome 浏览器中，打开 `chrome://extensions/`
            4. 开启"开发者模式"
            5. 点击"加载已解压的扩展程序"
            6. 选择解压后的文件夹
            
            ## 功能列表
            
            - 身份证生成器
            - 身份证解析器
            - 时间戳转换
            - 字符串编码
            - 加密解密
            - WebSocket测试
            - 随机数生成
            - 图片转换
            - 图片处理
            - 网站图标生成器
            - 颜色工具
            - JSON格式化
            - 二维码工具
            - 正则表达式工具
            - 单位转换
          draft: false
          prerelease: false
